### ISSUE TITLE
Interestingly we come up with a similar idea in the same name

### ISSUE THREAD

**Issue by alvis** [akhil0001/Project__12--A#1]
Hi @akhil0001. My name is Alvis and I'm the author of another sherlog (https://github.com/alvis/sher.log).

It's interesting to connect another bug killer this way. Probably if I'm not about to publish my long overdue logger, I won't notice about your nice work. I just realise we come up with the same package name about 2 years ago and we both come with a similar motive to make debugging more pain-free. So fast-forward for 2 years, I'm finally picking it up again and would like to publish it. 

Just wondering if you would allow me to pick up the legacy of sherlog and continue to develop it? I'm very happy to continue to work on it if you could transfer me the ownership of the npm package to @alvis. Certainly, I respect if you'd like to keep it. ;)

**Comment by akhil0001** [comment]
Hey @alvis , good to know this. Will transfer ownership of the package now
